### ISSUE TITLE
Esto podría estar en el .env

### ISSUE THREAD

**Issue by julianbutti** [francobidart/dsw-tp-backend#1]
https://github.com/francobidart/dsw-tp-backend/blob/44d412f5e11594db1f0a85b6ec5a93c620f97389/config/config.json#L5

**Comment by francobidart** [comment]
Esto está definido así porque sequelize lo usa por defecto a ese archivo. Voy a ver si hay alguna forma de implementarlo a través de variables de entorno

**Comment by francobidart** [comment]
Fixed, ya se encuentra configurado para utilizar variables de entorno.

**Comment by francobidart** [comment]
Cambios en: https://github.com/francobidart/dsw-tp-backend/commit/0253af9601f9acf734ca55bbd7b9067ebd5028b7
