### ISSUE TITLE
Está medio cargado este archivo, algunas cosas podrían ir a archivos de route externos

### ISSUE THREAD

**Issue by julianbutti** [francobidart/dsw-tp-backend#2]
https://github.com/francobidart/dsw-tp-backend/blob/44d412f5e11594db1f0a85b6ec5a93c620f97389/app.js#L132

**Comment by francobidart** [comment]
Buenas noches profesor.

Se realizaron las modificaciones requeridas, se modificó la ubicación de las rutas. Separamos las rutas por tipo de endpoint para que las que correspondan a un mismo grupo se encuentren definidas en un archivo específico.

COMMIT: https://github.com/francobidart/dsw-tp-backend/commit/1e730c3886fecbb21e097a8eff8566cea01cf1df
